@startuml BookApi_ERModel

hide method
hide circle
skinparam DefaultFontName Helvetica
skinparam linetype ortho
left to right direction

package "Book Domain" {
    entity Author {
        * Id : int <<generated>>
        --
        * Name : string
    }

    entity Publisher {
        * Id : int <<generated>>
        --
        * Name : string
    }

    entity Book {
        * Id : int <<generated>>
        --
        * ISBN : string
        * Title : string
        * PublishedAt : DateTime
        * FKPublisher : int <<FK>>
    }

    entity BookAuthor {
        * BookId : int <<FK>>
        * AuthorId : int <<FK>>
        --
        * Order : int
    }

    Book ||..o{ Publisher
    Book }|..|| BookAuthor
    BookAuthor ||..o{ Author
}
@enduml