services:
  postgres:
    image: postgres:16.2-alpine
    container_name: bookapi-postgres
    restart: always
    expose:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: book-db
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 3s
      retries: 5

  api:
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: ../../src/
      dockerfile: Production.dockerfile
    image: bookapi-api
    container_name: bookapi-api
    environment:
      ConnectionStrings__DefaultConnection: "Server=postgres;Port=5432;Database=book-db;Username=postgres;Password=password"
    ports:
      - "5000:8080"

volumes:
  postgres-volume: